permissions:
  contents: write

name: run
on:
  workflow_dispatch:
  schedule:
    # run every hour
    - cron: "0 * * * *"

jobs:
  check:
    runs-on: ubuntu-22.04
    outputs:
      ok: ${{ steps.check.outputs.ok }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.12.0"

      - name: Check streak
        id: check
        env:
          TIMEZONE: "America/Montreal"
        run: |
          npm ci

          set +e
          npm start
          status=$?
          set -e

          echo "ok=$status" >> "$GITHUB_OUTPUT"
          exit 0

  save:
    needs: check
    if: needs.check.outputs.ok == '1'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Save streak
        run: |
          git config user.name "${GITHUB_REPOSITORY_OWNER}"
          git config user.email "${GITHUB_REPOSITORY_OWNER_ID}+${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"

          echo "$(date)" >> streak.txt
          git add streak.txt

          git commit -m "chore[streaksaver]: save streak"
          git push
